version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  back:
    restart: always
    container_name: back
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      BACK_PORT: 5000
      JWT_SECRET: SECRET
    build:
      context: ./back/
    command: yarn dev
    depends_on:
      - mysql
    volumes:
      - ./back/:/app/back
      - /app/back/node_modules
    ports:
      - "5000:5000"

  front:
    stdin_open: true
    restart: always
    container_name: front
    depends_on:
      - mysql
      - back
    build:
      context: ./front/
    command: yarn start
    volumes:
      - ./front/:/app/front
      - /app/front/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  db_mysql: {}
